hackathon_game_homepage:
    path:     /hello/{name}
    defaults: { _controller: HackathonGameBundle:Default:index }

game:
    resource: "@HackathonGameBundle/Controller/APIController.php"
    type:     annotation

emulator:
    resource: "@HackathonGameBundle/Controller/EmulatorController.php"
    type:     annotation
