<?php

namespace Hackathon\Bundle\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    /**
     * Returns the current game
     */
    public function findCurrentGame($includeNotStarted = true)
    {
	$games = $this->findBy(array(), array("id" => "DESC"), 1);
	$game = $games[0];

	// Check if we should include not started games
	if ($includeNotStarted == false) {
	    if ($game->isStarted() == false) {
		// The game is not yet started. We dont want it
		$game = $this->findBy(
		    array(
			'id' => ($game->getId() - 1)
		    )
		);
	    }
	}

	return $game;
    }


}
