<?php

namespace Hackathon\Bundle\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    /**
     * Returns the current game
     */
    public function findCurrentGame()
    {
	$games = $this->findBy(array(), array("id" => "DESC"), 1);
	return $games[0];
    }

}
