<?php

namespace Hackathon\Bundle\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameTurnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTurnRepository extends EntityRepository
{
}
